backend:
  name: git-gateway

media_folder: /assets/media/uploads
#publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "collections/_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - {name: "title", label: "Title", widget: "string"}
      - {name: "image", label: "Featured Image", widget: "image", required: false}
      - {name: "body", label: "Body", widget: "markdown", required: false}

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "collections/_pages"
    create: true
    editor:
      preview: false
    fields:
      - {name: "permalink", label: "Slug", widget: "string", hint: "Custom URL for this page (defaults to title-based slug)", required: false}
      - {name: "title", label: "Title", widget: "string", hint: "The title of the page"}
      - {name: "description", label: "Description", widget: "text", hint: "The description of the page for SEO (defaults to site description)", required: false}
      - {name: "image", label: "Sharing Image", widget: "image", hint: "Page image for sharing on social networks (defaults to site image)", required: false}
      - {name: "body", label: "Body", widget: "markdown", hint: "The content for the page", required: false}
      - name: "sections"
        label: "Sections"
        hint: "The content sections that will appear on the page"
        label_singular: "Section"
        widget: "list"
        required: false
        fields:
          - {name: "section", label: "Section", widget: "relation", collection: "sections", displayFields: ["title"], searchFields: ["title"], valueField: "title", required: false}
          - {name: "carousel", label: "Carousel", widget: "relation", collection: "carousels", displayFields: ["title"], searchFields: ["title"], valueField: "title", required: false}

  - name: "sections"
    label: "Sections"
    delete: false
    editor:
      preview: false
    files:
      - name: "about"
        label: "About"
        file: "collections/_sections/about.md"
        description: "About US"
        fields:
          - {name: "title", label: "Title", widget: "string"}
          - {name: "body", label: "Body", widget: "markdown", required: false}
          - {name: "image", label: "Image", widget: "image", required: false}

      - name: "posts"
        label: "Posts"
        file: "collections/_sections/posts.md"
        description: "Posts"
        fields:
          - {name: "title", label: "Title", widget: "string"}
          - {name: "body", label: "Body", widget: "markdown", required: false}
          - {name: "view", label: "View", widget: "select", options: ["grid", "list"], default: "grid", required: false}
          - {name: "items", label: "Items", widget: "number", default: "6", required: false}

      - name: "numbers"
        label: "Numbers"
        file: "collections/_sections/numbers.md"
        description: "Stats"
        fields:
          - {name: "title", label: "Title", widget: "string"}
          - {name: "body", label: "Body", widget: "markdown", required: false}
          - name: "numbers"
            label: "Numbers"
            label_singular: "Number"
            widget: "list"
            required: false
            fields:
              - {name: "number", label: "Number", widget: "number", required: false}
              - {name: "prefix", label: "Prefix", widget: "string", required: false}
              - {name: "suffix", label: "Suffix", widget: "string", required: false}
              - {name: "title", label: "Title", widget: "string", required: false}
              - {name: "animate", label: "Animate", widget: "boolean", default: true}

      - name: "clients"
        label: "Clients"
        file: "collections/_sections/clients.md"
        description: "Clients"
        fields:
          - {name: "title", label: "Title", widget: "string"}
          - {name: "body", label: "Body", widget: "markdown", required: false}
          - name: "clients"
            label: "Clients"
            label_singular: "Client"
            widget: "list"
            required: false
            fields:
              - {name: "organization", label: "Organization", widget: "relation", collection: "organizations", displayFields: ["title"], searchFields: ["title"], valueField: "title", required: false}

      - name: "team"
        label: "Team"
        file: "collections/_sections/team.md"
        description: "Team Members"
        fields:
          - {name: "title", label: "Title", widget: "string"}
          - {name: "body", label: "Body", widget: "markdown", required: false}
          - name: "people"
            label: "People"
            label_singular: "Person"
            widget: "list"
            required: false
            fields:
              - {name: "person", label: "Person", widget: "relation", collection: "people", displayFields: ["title", "company", "position"], searchFields: ["title", "company", "position"], valueField: "title", required: false}

  - name: "carousels"
    label: "Carousels"
    label_singular: "Carousel"
    folder: "collections/_carousels"
    create: true
    editor:
      preview: false
    fields:
      - {name: "title", label: "Name", widget: "string", hint: "The name of the carousel"}
      - name: "slides"
        label: "Slides"
        label_singular: "Slide"
        widget: "list"
        required: false
        fields:
          - {name: "title", label: "Title", widget: "string", required: false}
          - {name: "body", label: "Body", widget: "markdown", required: false}
          - {name: "image", label: "Image", widget: "image", required: false}
          - name: "button"
            label: "Button"
            widget: "object"
            required: false
            fields:
              - {name: "title", label: "Title", widget: "string", required: false}
              - {name: "url", label: "URL", widget: "string", required: false}
              - {name: "type", label: "Type", widget: "select", options: ["primary", "secondary", "success", "danger", "warning", "info", "link"], required: false}

  - name: "people"
    label: "People"
    label_singular: "Person"
    folder: "collections/_people"
    create: true
    editor:
      preview: false
    fields:
      - {name: "title", label: "Name", widget: "string"}
      - {name: "company", label: "Company", widget: "string", required: false}
      - {name: "position", label: "Position", widget: "string", required: false}
      - {name: "image", label: "Image", widget: "image", required: false}
      - {name: "author", label: "Is an Author?", widget: "boolean", default: false}
      - name: "contacts"
        label: "Contacts"
        description: "Public Contacts"
        widget: "object"
        required: false
        fields:
          - {name: "Email", label: "Email", widget: "string", required: false}
          - {name: "LinkedIn", label: "LinkedIn", widget: "string", required: false}
          - {name: "Twitter", label: "Twitter", widget: "string", required: false}
          - {name: "Instagram", label: "Instagram", widget: "string", required: false}
          - {name: "Medium", label: "Medium", widget: "string", required: false}
          - {name: "Facebook", label: "Facebook", widget: "string", required: false}

  - name: "organizations"
    label: "Organizations"
    label_singular: "Organization"
    folder: "collections/_organizations"
    create: true
    editor:
      preview: false
    fields:
      - {name: "title", label: "Name", widget: "string"}
      - {name: "logo", label: "Logo", widget: "image", required: false}
      - {name: "url", label: "URL", widget: "string", required: false}
      - {name: "industry", label: "Industry", widget: "string", required: false}
      - {name: "type", label: "Type", widget: "select", options: ["Company", "Brand", "Client", "Sponsor", "Partner", "Media Partner"], required: false}

  - name: "navigation"
    label: "Navigation"
    delete: false
    editor:
      preview: false
    files:
      - name: "header"
        label: "Header"
        file: "collections/_navigation/header.md"
        description: "Header Navigation"
        fields:
          - name: "items"
            label: "Items"
            label_singular: "Item"
            widget: "list"
            required: false
            fields:
              - {name: "title", label: "Title", widget: "string", hint: "Link label (defaults to page title, or URL address)", required: false}
              - {name: "page", label: "Page", widget: "relation", collection: "pages", displayFields: ["title"], searchFields: ["title"], valueField: "title", hint: "Choose a page...", required: false}
              - {name: "url", label: "External URL", widget: "string", default: "https://", hint: "...or link to an external URL", required: false}
      - name: "footer"
        label: "Footer"
        file: "collections/_navigation/footer.md"
        description: "Footer Navigation"
        fields:
          - name: "items"
            label: "Items"
            label_singular: "Item"
            widget: "list"
            required: false
            displayFields: ["page", "title", "url"]
            fields:
              - {name: "title", label: "Title", widget: "string", hint: "Link label (defaults to page title, or URL address)", required: false}
              - {name: "page", label: "Page", widget: "relation", collection: "pages", displayFields: ["title"], searchFields: ["title"], valueField: "title", hint: "Choose a page...", required: false}
              - {name: "url", label: "External URL", widget: "string", default: "https://", hint: "...or link to an external URL", required: false}

  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "General"
        file: "collections/_settings/general.md"
        description: "General Site Settings"
        fields:
          - {name: "title", label: "Site Title", widget: "string"}
          - {name: "description", label: "Site Description", widget: "text", required: false}
          - {name: "logo", label: "Site Logo", widget: "image", required: false}
          - {name: "image", label: "Share Image", widget: "image", required: false}
          - {name: "search", label: "Site Search", widget: "boolean", default: true}
          - {name: "email", label: "Site Email", widget: "string", required: false}
          - {name: "phone", label: "Site Phone Number", widget: "string", required: false}
          - name: "social"
            label: "Social"
            description: "Social Networks"
            widget: "object"
            required: false
            fields:
              - {name: "LinkedIn", label: "LinkedIn", widget: "string", required: false}
              - {name: "Twitter", label: "Twitter", widget: "string", required: false}
              - {name: "Instagram", label: "Instagram", widget: "string", required: false}
              - {name: "Medium", label: "Medium", widget: "string", required: false}
              - {name: "Facebook", label: "Facebook", widget: "string", required: false}
              - {name: "Youtube", label: "Youtube", widget: "string", required: false}
              - {name: "GitHub", label: "GitHub", widget: "string", required: false}
      - name: "integrations"
        label: "Integrations"
        file: "collections/_settings/integrations.md"
        description: "3rd Party Integrations"
        fields:
          - {name: "google_analytics", label: "Google Analytics Tag", widget: "text", required: false}
          - {name: "google_maps", label: "Google Maps Key", widget: "string", required: false}
          - {name: "facebook_app_id", label: "Facebook App ID", widget: "string", required: false}
          - {name: "newsletter", label: "Newsletter TAG", widget: "text", hint: "Mailchimp, Mailerlite, etc", required: false}
